plugins {
    id 'com.android.application'
    id 'kotlin-android'
}
android {
    compileSdkVersion 30
    defaultConfig {
        applicationId "com.vhall.vhlive"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 6250
        versionName "$app_version"
    }

//    signingConfigs {
//        release {
//            storeFile file("vhall_android_app.keystore")
//            storePassword ''
//            keyAlias ''
//            keyPassword ''
//        }
//        debug {
//            storeFile file("vhall_android_app.keystore")
//            storePassword ''
//            keyAlias ''
//            keyPassword ''
//        }
//    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
//            signingConfig signingConfigs.release
            //使用美颜打包时移除多余资源文件减小打包体积
            applicationVariants.all { variant ->
                variant.mergeAssetsProvider.configure {
                    doLast {
                        delete(fileTree(dir: outputDir,
                                includes: ['model/ai_bgseg_green.bundle',
                                           'model/ai_face_processor_lite.bundle',
                                           'model/ai_hairseg.bundle',
                                           'model/ai_face_processor.bundle',
                                           'model/ai_hand_processor.bundle',
                                           'model/ai_human_processor_mb_fast.bundle',
                                           'model/ai_human_processor.bundle',
                                           'graphics/controller_cpp.bundle',
                                           'graphics/fuzzytoonfilter.bundle',
                                           'graphics/body_slim.bundle',
                                           'graphics/face_makeup.bundle',
                                           'graphics/tongue.bundle',
                                           'graphics/fxaa.bundle']))
                    }
                }
            }

        }

        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
//            signingConfig signingConfigs.release
        }
    }
    buildFeatures {
        viewBinding true
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lintOptions {
        abortOnError false
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation project(':uilibs')
    implementation 'com.alibaba:fastjson:1.2.73'
    api 'com.tencent.mm.opensdk:wechat-sdk-android:6.8.34'
}
repositories {
    mavenCentral()
}
